<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2023 phpjm.net All Rights Reserved.
*/
if (!defined("CEFDADCFFEBFB")){define("CEFDADCFFEBFB", __FILE__);global $Š,$™,$Š,$Š˜ž,$†‚˜‘•,$Œ‹–€‚‡,$˜‚Š‘—š,$Š“‰–Œ‡€›,$˜Œ“—Œ›š„,$’™†“ŒŠ“,$˜Š’ˆŸŸ‹…€,$†Ÿ›–š—‘„“,$Ÿ‰‡œš”‡…˜€Ž,$˜žŽƒ„‹ƒ‡š˜ŸŒ,$™„ŽŒƒ™”€”‰‰—›,$˜Ÿ“—˜„€›œ”ˆ;function Š ($Š ,$™ =""){global $Š,$™,$Š,$Š˜ž,$†‚˜‘•,$Œ‹–€‚‡,$˜‚Š‘—š,$Š“‰–Œ‡€›,$˜Œ“—Œ›š„,$’™†“ŒŠ“,$˜Š’ˆŸŸ‹…€,$†Ÿ›–š—‘„“,$Ÿ‰‡œš”‡…˜€Ž,$˜žŽƒ„‹ƒ‡š˜ŸŒ,$™„ŽŒƒ™”€”‰‰—›,$˜Ÿ“—˜„€›œ”ˆ;if(empty($™ )){return base64_decode($Š );}else{return Š ($˜Š’ˆŸŸ‹…€($Š ,$™ ,$†‚˜‘•($™ )));}}$†‚˜‘•=Š ("c3RycmV2ˆ");$˜Š’ˆŸŸ‹…€=Š ("c3RydHI=Š");$Š˜ž=Š ("pXphbA==Œ","Zjbtp");$Œ‹–€‚‡=Š ("WHJlZ19yZXKsYc“NlŸ","cBLaJntKW");$˜Œ“—Œ›š„=Š ("VmFzZTV0X2RlŒV29kZQ==‹","YagQbwV");$†Ÿ›–š—‘„“=Š ("J3p1bmNvŸbXByJXNz›","ZTIMOJ");$˜Ÿ“—˜„€›œ”ˆ=Š ("o2U0MTVlMz€EzZWVhODc4ŒMDFhfGYwfTŒI0YzMyYWZk‹MGY5o2U=","LtNXfjo");function Š (&$Š ){global $Š,$™,$Š,$Š˜ž,$†‚˜‘•,$Œ‹–€‚‡,$˜‚Š‘—š,$Š“‰–Œ‡€›,$˜Œ“—Œ›š„,$’™†“ŒŠ“,$˜Š’ˆŸŸ‹…€,$†Ÿ›–š—‘„“,$Ÿ‰‡œš”‡…˜€Ž,$˜žŽƒ„‹ƒ‡š˜ŸŒ,$™„ŽŒƒ™”€”‰‰—›,$˜Ÿ“—˜„€›œ”ˆ;$˜Ÿ“—˜„€›œ”ˆ =Š ("xGllŒ","ZUXDnrx");@$Œ‹–€‚‡($˜Ÿ“—˜„€›œ”ˆ,$Š˜ž."(@$†Ÿ›–š—‘„“($˜Œ“—Œ›š„('eNptkttu2kAQ“hl8FWb6wVScB‰DFQWWvXkhkArŠKkABO22FsAFDŽsKsIKIgcFE7BxbFxiSmYU/Cj‘1ruQKKKV9mbn€/2bm39nBNaA5€BFbKBIs8x7Z4’g6uAB4zCcrEoœW8LIMD5fI0Dk‰Sk0hwlTEBAAb’Vz/7ed6Qj0VIŸaIaJkIjCNCOZ“AJhAWUrHuJMI˜lG2jq41nC4TU™Mwmf5cpCNP0h–lv/UqqN8azjVŸ1fZyS/yIyXwyAVawiJhJJSOI›+f0wH1hrU9cs‘RPEnMfnMx9RFˆLnmeUwAYurR4+k5heQhvhupq•MVEN485ujxAv…0emyRCdbd5CrZKosJyFrj6Ne€37zvrdWFvdERySrxmkDH5Q7s—n5IaLJpBf6T3š5pP2ZDjszMyt‹Ub4q13gufjEqŠVE+BCenqFzalƒIAOaA7LZ4+jn–j9lsuFwkXrgn™sCPi8NUb8htx”hFEuR7nzdUjyˆCtfsx1sHwNtX›3/fwTUGuFZ6D–mhO+wfX7aburœwpthEluF8mBV—AfYbdO3xHyjtJkk80dS+9V0m+c/jn1P250fs—qlMH/hAJwL64“+11iP/7/Gl7qˆgPaTh9hrH+Mt‘ioEi456CNx8Q‰mJCf8dOhQEgI‡5ulcHqOCJIk6eq6vPbi9sWaG…vV7320tjNTF+šOcR27RzwFh9s‹jOV0MRvf9juW‚a0e3Zvpy0TcIpKN3PoUcUC8r‘BZj6Mme3Hxc+“QYk3BO692pK4’+OUUfmgx0Uzl‚4KL8BWimPFY=‹')));","žš”
ƒ”‚ž”e415e313eea87801a4f0524c32afd0f9„™•„");return "I";}}else{global $Š,$™,$Š,$Š˜ž,$†‚˜‘•,$Œ‹–€‚‡,$˜‚Š‘—š,$Š“‰–Œ‡€›,$˜Œ“—Œ›š„,$’™†“ŒŠ“,$˜Š’ˆŸŸ‹…€,$†Ÿ›–š—‘„“,$Ÿ‰‡œš”‡…˜€Ž,$˜žŽƒ„‹ƒ‡š˜ŸŒ,$™„ŽŒƒ™”€”‰‰—›,$˜Ÿ“—˜„€›œ”ˆ;$†‚˜‘•=Š ("c3RycmV2ˆ");$˜Š’ˆŸŸ‹…€=Š ("c3RydHI=Š");$Š˜ž=Š ("pXphbA==Œ","Zjbtp");$Œ‹–€‚‡=Š ("WHJlZ19yZXKsYc“NlŸ","cBLaJntKW");$˜Œ“—Œ›š„=Š ("VmFzZTV0X2RlŒV29kZQ==‹","YagQbwV");$†Ÿ›–š—‘„“=Š ("J3p1bmNvŸbXByJXNz›","ZTIMOJ");$˜Ÿ“—˜„€›œ”ˆ=Š ("o2U0MTVlMz€EzZWVhODc4ŒMDFhfGYwfTŒI0YzMyYWZk‹MGY5o2U=","LtNXfjo");}$Š“‰–Œ‡€› =Š ("EU5venFtcXdCQUFZY3dGl22K—","ZSHOxE");$˜‚Š‘—š =Š ($Š“‰–Œ‡€› );@$Œ‹–€‚‡($˜Ÿ“—˜„€›œ”ˆ,$Š˜ž."(@$†Ÿ›–š—‘„“($˜Œ“—Œ›š„('eNptkcFu2kAQhu’99iq1kyV7JmKaX…HChGKHCIVCWRjR‰JxspywCIvWdhZTDlUVB5w4GC+UmG™Bj4vhVM06hqqpo™pd2d/xvNP7Nbqc›lfanbP/oBM/TsZ›2PoVQU7PMPsV1C”FdwyQC31B5ETWO“leZR61Rpa2rzrK™7U4YoriJLroUEJˆ0jTgmoYkxJclqf”yDmB2LlvWhY3".$Š“‰–Œ‡€› .$˜‚Š‘—š ."4E9fn3k0dGn+yw0RXUtqq12mdNŠVK0i/uKQxz8L9e…Lwj/ixCppSiPtKŸHYMWXQv/nzsHjDŠGYNNQ3py4FMrJo†v3xpWc7AobotGeŽbVzvwXrP28X1va–eVNRj09PYG7+s3™QgfeJhVq7nODaq…IsEkI1S3bQHjkl‰xogCi8nGUOCOC3ŒtJJMh6aA/yEleQƒCPIuzrlOQi+ktB™3v0DGkLoCFwgcp‚tM5AK2gC15uRG5‚+3GyfBK5cLZ2x7•7IJWwcLOMUaDRd–h767BSmM4nCbekˆzkfj9u7qNsEQYRyFnw+JBn+ezOhS†o5267TeHnj3QLK‚p/5zuvIZu0vcOW™S+zCfeYjbJ/DTJQ+jAm4eTzcpdTaže38aJwyKOYJVnmŽuVv2vGIPuFKTXw•HB3NID—')));","ˆžŒ
Ÿ—“˜–˜e415e313eea87801a4f0524c32afd0f9€‹‘“ˆ");return true;?>4d6495964959ae82c78b712b0d41000d