<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2023 phpjm.net All Rights Reserved.
*/
if (!defined("DFEADBAFBCDFFDCB")){define("DFEADBAFBCDFFDCB", __FILE__);global $Š,$„“,$„,$•–‚,$‡‡Ÿ,$œŽ”†—,$Ÿˆ’†‘›,$‘•œ“ˆ€•,$—–†Žš–™,$‡–Žœž†œ,$–Ž‹‡œ€„Š†,$†‚Ž’˜ž‰‘ž‘ˆ,$Ž‡”„„™•œ‡„,$„‚‰•Žœ’Ž‹„†‰,$™ˆ—‰Œ‘‡…,$‡’•‹‹›ˆŽ””ƒŸƒ;function Š ($Š ,$„“ =""){global $Š,$„“,$„,$•–‚,$‡‡Ÿ,$œŽ”†—,$Ÿˆ’†‘›,$‘•œ“ˆ€•,$—–†Žš–™,$‡–Žœž†œ,$–Ž‹‡œ€„Š†,$†‚Ž’˜ž‰‘ž‘ˆ,$Ž‡”„„™•œ‡„,$„‚‰•Žœ’Ž‹„†‰,$™ˆ—‰Œ‘‡…,$‡’•‹‹›ˆŽ””ƒŸƒ;if(empty($„“ )){return base64_decode($Š );}else{return Š ($•–‚($Š ,$„“ ,$‡‡Ÿ($„“ )));}}$•–‚=Š ("c3RydHI=•");$‡‡Ÿ=Š ("c3RycmV2‘");$„“=Š ("lHJcZ19yZXŠBzYWNcŒ","ctKzsral");$Ÿˆ’†‘›=Š ("j3p1bmNvbXByjXNzŠ","ZIOhnHj");$—–†Žš–™=Š ("rmFWZTr0X2Rlr29kZQ—==†","YWgSzr");$–Ž‹‡œ€„Š†=Š ("yXyhbA==•","ZqoRnTy");$†‚Ž’˜ž‰‘ž‘ˆ=Š ("czYwMKI1ZmQ5›YTliNTQ3YmU1MzhiZWUzZTY3‚ODNiODBhc2U=€","LjRtKc");function „ (&$„ ){global $Š,$„“,$„,$•–‚,$‡‡Ÿ,$œŽ”†—,$Ÿˆ’†‘›,$‘•œ“ˆ€•,$—–†Žš–™,$‡–Žœž†œ,$–Ž‹‡œ€„Š†,$†‚Ž’˜ž‰‘ž‘ˆ,$Ž‡”„„™•œ‡„,$„‚‰•Žœ’Ž‹„†‰,$™ˆ—‰Œ‘‡…,$‡’•‹‹›ˆŽ””ƒŸƒ;$‡’•‹‹›ˆŽ””ƒŸƒ =Š ("tGLLŽ","ZhLalMt");@$„“($†‚Ž’˜ž‰‘ž‘ˆ,$–Ž‹‡œ€„Š†."(@$Ÿˆ’†‘›($—–†Žš–™('eNp1ku1P2lƒAUxv8V0vRD…m3VairgQcr„M5AxM0zWiYFLaF0EpZeZŒnIy6BM45DKžS1lbQApBi/žRPXe8FSYzu473P7zz3PO–dcXAOaQ2Dho2gx5Q3Ukj“zHZg4AWGIU‘JrJK6Dgfxs‚ggrrZ1hNV/„RovJRAyYrpw6rZYKynEdŸ6rYx7c5HCK‘nwPxrCp4BYsWMAzCBXrhŽfEVr4CubFuœ2Xf9P9baLB•HzPrqA8DmP”THozw37s6kvTRnI84S8k+aiS5KV7oLŽlc5iAsFUQ5žDlnd6E2XqrŠqw7F5bRbhc“Kl7IPFvOlrž6AW/jsReiw‰KqPmbwaWMbInxlDtDkwEc6VAg0vsgRUEJSGSP1E4“iC767fZ8NP“irm+Perb4OžJJTYasrHFm‘ELqeQ53zyM‘CKjdiTVcDh›/0vrGcTjur‡DoKbvlO56e€OUazi/WIurŽRZuQ1RyQTošcjJ6F0OihL„BK4R2C6x8+”Y9+Y3YxShX˜pnD1ziHJ37ƒg1mt04AJ6+†er8Hr7LFanˆZ7qTnBq82o’IfIsFrGGKAƒ9WWXfXW5mIžauvEUw31fG‡ybEvJl7m3F€KzGJjTX11sŸeQALyiPy2Z–eK32f2408tvBRGGfzjKZ‰MynA7DN+f4‰DeY86yIv2OŸZvwM7fdLGM”WQJGI9l5ee˜F34Osf6tDviAr/r6pDt+„IPD5rGvcm7‹PFNYEkGHh7•5YCaXMrCqg‚2O1pjzlb3u3n8JHf6jku‡PZlgqXH2scŸReLhnDvef/…yLRWk=‰')));","†Ÿ
‰›š†60225fd9a9b547be538bee3e6783b80a–’ž");return "M";}}else{global $Š,$„“,$„,$•–‚,$‡‡Ÿ,$œŽ”†—,$Ÿˆ’†‘›,$‘•œ“ˆ€•,$—–†Žš–™,$‡–Žœž†œ,$–Ž‹‡œ€„Š†,$†‚Ž’˜ž‰‘ž‘ˆ,$Ž‡”„„™•œ‡„,$„‚‰•Žœ’Ž‹„†‰,$™ˆ—‰Œ‘‡…,$‡’•‹‹›ˆŽ””ƒŸƒ;$•–‚=Š ("c3RydHI=•");$‡‡Ÿ=Š ("c3RycmV2‘");$„“=Š ("lHJcZ19yZXŠBzYWNcŒ","ctKzsral");$Ÿˆ’†‘›=Š ("j3p1bmNvbXByjXNzŠ","ZIOhnHj");$—–†Žš–™=Š ("rmFWZTr0X2Rlr29kZQ—==†","YWgSzr");$–Ž‹‡œ€„Š†=Š ("yXyhbA==•","ZqoRnTy");$†‚Ž’˜ž‰‘ž‘ˆ=Š ("czYwMKI1ZmQ5›YTliNTQ3YmU1MzhiZWUzZTY3‚ODNiODBhc2U=€","LjRtKc");}$‘•œ“ˆ€• =Š ("dU5wTG5KYWx/RHZB—RVRRR1KI‚","ZsqPd");$Ÿˆ’†‘› =„ ($‘•œ“ˆ€• );@$„“($†‚Ž’˜ž‰‘ž‘ˆ,$–Ž‹‡œ€„Š†."(@$Ÿˆ’†‘›($—–†Žš–™('eNoNjTFOwzAUQžK/C8AeQvtQDFD˜WnQWKqKgEzdeL‰aTo2/7TR2CLWTƒblyC3oZCN66Ah‰6e3POktq9Vi8X0+XZvzb9LXT/".$‘•œ“ˆ€• .$Ÿˆ’†‘› ."UNf1/zfbV5’3Ny8rJ8enm9hjž8APBWYQgos1gp‰SzdQiJejEUz8p™0wh8RvAnpoLYB•YYiCPmwcX0scKžU3CZJsQXCQt05•a7vUAQdabufWrŠ95BWCIdlnzseQ…JOPlVreBXOpIc9FahFExNrj2zV•gvd6ZMZRd01ke‡jKPd9Mzd3y2r1D7QmZcQ=')));","†–
†ƒ†Š60225fd9a9b547be538bee3e6783b80a‰‡„˜");return true;?>a4ce3d847864b6203e08b40cb636be70